# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Riley Marcoux
tagline:          'Unfiltered Opinions'
description:      'Unfiltered Opinions'
url:              http://rmarcoux.com
baseurl:          /

paginate:         5

# Custom vars
version:          1.0

