# Base configs
baseurl: "https://rmarcoux.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-28340273-3"

# UI configs
title: "Photography by Riley Marcoux"
subtitle: "See the world through my eyes!"
author: "Riley Marcoux"
header:
 title: "Photography"
 subtitle: "by Riley Marcoux"
footer:
 name: "Hey there, my name is Riley"
 bio: "I am a Photographer and tech enthusiast from Canada. I love to share my photography and love for technology with everyone."
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/rileymarcoux"
  instagram: "https://www.instagram.com/rileymarcoux"
  linkedin: "https://in.linkedin.com/in/rileymarcoux"
