# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Riley Marcoux
tagline:          ''
description:      'Unfiltered Opinions'
url:              http://rmarcoux.com
baseurl:          /

author:
  name:           'Riley Marcoux'
  url:            https://rmarcoux.com

paginate:         5

# Custom vars
version:          2.1.0

