# Base configs
baseurl: "https://rmarcoux.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Riley Marcoux Photo"
subtitle: "London based automotive photographer"
author: "Riley Marcoux"
header:
 title: "Riley Marcoux Photo"
footer:
 name: "Hey there, my name is Riley"
 bio: "I am an automotive photographer base din London, Ontario."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/ram_patra"
  facebook: "https://www.facebook.com/marcouxphotography"
  flickr: "https://www.flickr.com/photos/197429934@N07"
